image: debian:bookworm-slim

stages:
  - test

before_script:
  - apt-get update
  - apt-get install -y --no-install-recommends dash git ca-certificates
  - rm -rf /var/lib/apt/lists/*

tests:
  stage: test
  script:
    - dash tests/run.sh